builds:
  -
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:latest
    - quay.io/mittwald/kubernetes-replicator-amd64:stable
    - quay.io/mittwald/kubernetes-replicator-amd64:v{{ .Major }}
    - quay.io/mittwald/kubernetes-replicator-amd64:v{{ .Major }}.{{ .Minor }}
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: amd64
    goarm: ''
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-arm64:latest
    - quay.io/mittwald/kubernetes-replicator-arm64:stable
    - quay.io/mittwald/kubernetes-replicator-arm64:v{{ .Major }}
    - quay.io/mittwald/kubernetes-replicator-arm64:v{{ .Major }}.{{ .Minor }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: arm64
    goarm: ''
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-armv5:latest
    - quay.io/mittwald/kubernetes-replicator-armv5:stable
    - quay.io/mittwald/kubernetes-replicator-armv5:v{{ .Major }}
    - quay.io/mittwald/kubernetes-replicator-armv5:v{{ .Major }}.{{ .Minor }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '5'
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-armv6:latest
    - quay.io/mittwald/kubernetes-replicator-armv6:stable
    - quay.io/mittwald/kubernetes-replicator-armv6:v{{ .Major }}
    - quay.io/mittwald/kubernetes-replicator-armv6:v{{ .Major }}.{{ .Minor }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '6'
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-armv7:latest
    - quay.io/mittwald/kubernetes-replicator-armv7:stable
    - quay.io/mittwald/kubernetes-replicator-armv7:v{{ .Major }}
    - quay.io/mittwald/kubernetes-replicator-armv7:v{{ .Major }}.{{ .Minor }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '7'
docker_manifests:
  - 
    name_template: quay.io/mittwald/kubernetes-replicator:latest
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
  - 
    name_template: quay.io/mittwald/kubernetes-replicator:stable
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
  - 
    name_template: quay.io/mittwald/kubernetes-replicator:v{{ .Major }}
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
  - 
    name_template: quay.io/mittwald/kubernetes-replicator:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
  - 
    name_template: quay.io/mittwald/kubernetes-replicator:{{ .Tag }}
    image_templates:
    - quay.io/mittwald/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-arm64:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv5:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv6:{{ .Tag }}
    - quay.io/mittwald/kubernetes-replicator-armv7:{{ .Tag }}
