apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-replicator.name" . }}
    helm.sh/chart: {{ include "kubernetes-replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubernetes-replicator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - --prefix
        - {{ template "kubernetes-replicator.prefix" . }}
        ports:
          - name: health
            containerPort: 9102
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "kubernetes-replicator.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
