apiVersion: v1
kind: Secret
metadata:
  name: secret1
  annotations:
    pr-1.preview.kubernetes-replicator.olli.com/replication-allowed: "true"
    pr-1.preview.kubernetes-replicator.olli.com/replication-allowed-namespaces: "test"
type: Opaque
stringData:
  source: secret1
